"""cria romancista

Revision ID: 18ae6b50d74d
Revises: cf114405d41a
Create Date: 2025-11-03 07:54:04.963675

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '18ae6b50d74d'
down_revision: Union[str, Sequence[str], None] = 'cf114405d41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
